[package]
name = "redis"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "redis"
path = "src/main/redis.rs"

[dependencies]
anyhow = "1.0.91"
log = "0.4.22"
tokio = { version = "1.41.0", features = ["full"] }
env_logger = "0.11.5"
lazy_static = "1.5.0"